swagger: '2.0'
info:
  title: 'stc - GCT Platform - APIs'
  description: |
      stc, a leading digital telecommunication corporation, has developed the GCT APIs to assist organizations to manage and utilize their owned SIMs in a manner that provides them managed connectivity in multi-national, multi-level, and multi-operator environments.
        ## Flow
        ```
        +------------+             +---------+            +----------+         
        |  Consumer  |             |  APIM   |            |  Target |
        +------------+             +---------+            +----------+      
              |                         |                       |     
              |   1- Consumer Request   |                       |                 
              |   ------------------>>  |                       |  
              |                                                 |
              |              2- APIM validates the request      |
              |                                                 |
              |   3- Validation Failure |                       |  
              | <<----------------------|                       |
              |                         |    3- Target Request  |  
              |                         |  ------------------>> |  
              |                         |                       |  
              |                         |    4-Target Response  |  
              |                         | <<------------------- |  
              |                         |                       |  
              |  5- Consumer Response   |                       |  
              | <<----------------------|                       |  
              |                         |                       |  
        ```
      
      
      ### Consumer(s) of API
      - **Partner Consumers**
        - OEM
        
      
      ## API Connectivity 
      ### Partner Host
        - **URL**
        Below is the base URL of internal hosts
         ```
              Live [Production]:  https://partner.api.stc.com.sa/gctPlatformMgmt/enterprise/v1  
              Sandbox [Preprod]:  https://sandbox.api.stc.com.sa:9522/gctPlatformMgmt/enterprise/v1
         ```
          
        - **Connectivity Details**
        Below is the connectivity details of internal host.
          | Environment |  FQDN |   Port      |  IP   | 
          |--------|-------|-------|------------|
          | **Sandbox [Pre-production]** | sandbox.api.stc.com.sa |9512 | 10.22.192.13
          | **Production** | partner.api.stc.com.sa |443 | 10.22.207.20         
          | **Disaster Recovery [DR]** | partner.api.stc.com.sa |443 | 10.18.223.29 
          
      # Release notes
      | Version |  Author   |   Date      |  Notes   | 
      |--------|-------  | -------|------------|
      | 1.0 |Walid Sadiq  &nbsp;  |  24th October 2022 | CR-50758 - GCT_IOT new platform project. 
  version: '1.0.0'
  termsOfService: https://developers.stc.com.sa/terms-and-conditions
  contact:
    name: API Team
    url: https://developers.stc.com.sa
    email: api@stc.com.sa
schemes:
  - https
host:  partner.api.stc.com.sa #partner.api.stc.com.sa (for Prod environment)
                               #sandbox.api.stc.com.sa:9512 (for Pre-prod environment)
basePath: '/gctPlatformMgmt/enterprise/v1'
securityDefinitions:
  OAuth2ClientCredentials:
    type: oauth2
    description: |
      Authorization using OAuth 2.0 protocol using the Client Credentials grant type. You must obtain a valid stc OAuth 2.0 access token with the relevant scope to use this method of authorization.
      
      Example: ```Authorization: Bearer AbCdEf123456```
      
      The string ```AbCdEf123456``` in the example above is the bearer authorization token. 
    tokenUrl: 'https:/api.stc.com.sa/s-oidc/oAuth2/v1/token'
    flow: password
    scopes:
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/voiceusage.read': read sim voice usage information
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/dataUsage.read': read sim data usage information
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/attachServicePlan.create': To attach new service plan to the device
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sms/send': send sms
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/account.read': To retrieve the details of the account
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/cancelLocation.create': disconnect sim from network
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/latestRegistration.read': read latest sim network registration
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/activationTrend.read' : To fetch the SIM Activation report
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/dataSessionCount.read' : To fetch the SIM Activation report      
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/ping': ping current api for healthcheck
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/account.read': To retrieve the details of the account
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/dataUsage.read': read device data usage information
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/users/userId.read': To fetch the details of the user through its userID
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/sessionHistory.read': To get the CDR details
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/smsusage.read': read message usage information
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/changeState.update' : update sim's current state
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/info.read': read sim info
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/downlink/usage.read': To fetch downlink data usage report.
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/alias.update': To update SIM Alias
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/users.read': To fetch the details of the user
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/sessionInfo.read': To fetch the details of the current device session
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/vehicleIdentificationNumber.update': To update the VIN
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/state.read': To get the current sim state
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/bundleDetails.read': to get Voice, SMS, and data bundle
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/uplink/usage.read': To fetch uplink data usage report.
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/audit.read': To get the audit history of the SIM
      'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/sessionWiseDataUsage.read': To fetch the details of data usage sessions
paths: 
  '/sims/voice/usage':
      get:
        tags:
          - Sim
        description: This API is used to get SMS usage based on selective criteria
        summary: To get voice usage of the selective criteria
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/voiceusage.read'
  '/sims/data/usage':
      get:
        tags:
          - Sim
        description: This API fetches the consolidated data usage details of a SIM for a particular time period. This detail can be fetched for a single or multiple SIM in a group.
         <br/><br/>```Filter Activities - By Offset and Limit (Paging)```<br/>
         Following query parameters should be supplied by client, If not provided service will return a partial response considering
         with default values of offset i.e. '0' and limit i.e. '20'. 
         <ul style='list-style-type:square'>
           <li>offset</li>
           <li>limit</li>         
         </ul>
        summary: To fetch consolidated data usage details of the SIM.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/dataUsage.read'
  '/device/attachServicePlan':
      post:
        tags:
          - Device
        description: This API is called to assign the new service plan to the device.
        summary: To attach new service plan to the device.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/attachServicePlan.create'
  '/sms/send':
      post:
        tags:
          - SMS
        description: This API is used to send SMS to a specific SIM.
        summary: To send SMS to a specific SIM.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sms/send'
  '/account/{id}':
      get:
        tags:
          - Account
        description: 
          This set of APIs fetch various details about an account including
          account name, parent account, unique id, account state and creation
          date. AccountID will be passed and a single-entry detail of the searched
          account will be returned.
        summary: To retrieve the details of the account
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/account.read'
  '/device/cancelLocation':
      get:
        tags:
          - Device
        description:
          This API will clear the subscriber data from previous MS/VLR and
          disconnects it from network, after this the device will reconnects to
          network itself.
        summary: This API will clear the subscriber data from MS/VLR.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/cancelLocation.create'
  '/device/latestRegistration':
      get:
        tags:
          - Device
        description:
          This API is called order to fetch latest SIM registration timestamp on
          the network along with network element address. It will output Network
          Registration Status, Last Registration Timestamp, Network Element Name
          and Network Element Address.
        summary: To get the latest SIM registration timestamp.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/latestRegistration.read'
  '/sims/activationTrend':
      get:
        tags:
          - Sim
        description: This API gives information about the number of SIMs activated in a particular  Group per month.
        summary: To fetch the SIM Activation report.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/activationTrend.read'
  '/sims/dataSessionCount':
      get:
        tags:
          - Sim
        description: This API fetches the number of session counts made by a SIM in a month.
        summary: To retrieve the SIM data session count.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/dataSessionCount.read'
  '/monitoring/ping':
      get:
        tags:
          - Ping
        description: Ping API.
        summary: Healthcheck ping API for.
        operationId: echo 
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/ping'             
  '/sims/account/{accountId}':
      get:
        tags:
          - Sim
        description: This API allows users to retrieve a list of all the SIMs assigned to an account based on the Account ID passed. The endpoints will return information regarding the SIM List.
         <br/><br/>```Filter Activities - By Offset and Limit (Paging)```<br/>
         Following query parameters should be supplied by client, If not provided service will return a partial response considering
         with default values of offset i.e. '0' and limit i.e. '10'. 
         <ul style='list-style-type:square'>
           <li>offset</li>
           <li>limit</li>         
         </ul>
        summary: Returns list of all SIMs assigned / allocated to an account.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/account.read'
  '/device/dataUsage':
      get:
        tags:
          - Device
        description: This API fetches the data usage details of the device.
        summary: To fetch the data usage details of the device.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/dataUsage.read'
  '/users/{id}':
      get:
        tags:
          - Users
        description: This API fetches the details of a particular user through its user ID.
        summary: To fetch the details of the user through its userID
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/users/userId.read'
  '/device/sessionHistory':
      get:
        tags:
          - Device
        description: This call fetches the CDR details according to the configured filtering options based on Start time and End time sessions.
        summary: To get the CDR details.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/sessionHistory.read'
  '/sims/sms/usage':
      get:
        tags:
          - Sim
        description: This API fetches the SMS usage details of a SIM against a selective criteria.
        summary: to get SMS usage of the selective criteria
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/smsusage.read'
  '/device/changeState':
      put:
        tags:
          - Device
        description: >-
          This API follows the Sync process for Device SIM State change. With this
          API, it is possible to request a change on SIM State by passing a
          desired state request and in return status of the request is received
          along with a reference ID. Note: When the Device is in Warm state, then
          the Device is registered first, and after that Device SIM state gets
          changed. SIM States: 1. Warm: - SIM assigned to enterprise but do not
          have access to data. Here, device will be registered first and then SIM
          state will be changed. 2. Activated: - SIM is considered “billable” and
          allowed to establish data connection. 3. Deactivated: -SIM is not
          considered “billable” and not allowed to establish data connection 4.
          Suspended: - Sim deployed to an account but temporarily made inactive.
          5. Retired: - SIM not allowed to establish data connection and has been
          physically removed from the network.
        summary: To update the SIM current state
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/changeState.update'
  '/sims':
      get:
        tags:
          - Sim
        description: >-
          This API is used to get multiple SIMs details by providing IMSI &
          ICCID in body parameters.
        summary: To get the details of sims whether it is single or multiple sim
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/info.read'
  '/sims/downlink/usage':
      get:
        tags:
          - Sim
        description: >-
          This API fetches the aggregated downlink usage details of a SIM for a
          month on a daily basis.
        summary: To fetch downlink data usage report.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/downlink/usage.read'
  '/sims/alias':
      put:
        tags:
          - Sim
        description: This API allows user to change alias similar to CMP web interface.
        summary: To update SIM Alias
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/alias.update'
  '/users':
      get:
        tags:
          - Users
        description: >-
          This API fetches the overall profile of user as created at the time of On-Boarding. This information can be filtered based on organizations.
        summary: To fetch the details of the user.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/users.read'
  '/device/sessionInfo':
      get:
        tags:
          - Device
        description: >-
          This API returns information about the current or most recent data
          session. This device information is fetched from BSS.
        summary: To fetch the details of the current device session.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/sessionInfo.read'
  '/device/vehicleIdentificationNumber':
      put:
        tags:
          - Device
        description: This API allows to update the Vehicle Identification Number (VIN).
        summary: To update the VIN
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/device/vehicleIdentificationNumber.update'
  '/sims/state':
      get:
        tags:
          - Sim
        description: This API fetches the current SIM state using ICCID or IMSI.
        summary: To get the current SIM State through ICCID or IMSI
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/state.read'
  '/sims/bundleDetails':
      get:
        tags:
          - Sim
        description: >-
          This API is used to get Voice, SMS, and data bundle from Airlinq
          External Systems (BSS) by passing IMSI in body parameters. For single and bulk SIMs
        summary: to get Voice, SMS, and data bundle from Airlinq External Systems (BSS).
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/bundleDetails.read'
  '/sims/uplink/usage':
      get:
        tags:
          - Sim
        description: >-
          This API fetches the aggregated uplink usage details of a SIM for a
          month on a daily  basis.
        summary: To fetch Uplink data usage report.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/uplink/usage.read'
  '/sims/audit/{iccid}':
      get:
        tags:
          - Sim
        description: >-
          This API is provided to allow Users to retrieve a list of all the
          changes applied to a SIM, identified by its deviceId i.e., ICCID, over a selected period of time. This API returns the logs of any activity performed for CMP UI (old value, new value of all modified fields) on a SIM during a given period.
           <br/><br/>```Filter Activities - By Offset and Limit (Paging)```<br/>
           Following query parameters should be supplied by client, If not provided service will return a partial response considering
           with default values of offset i.e. '0' and limit i.e. '10'. 
           <ul style='list-style-type:square'>
             <li>offset</li>
             <li>limit</li>         
           </ul>
        summary: To get the audit history of the SIM.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/audit.read'
  '/sims/sessionWiseDataUsage':
      get:
        tags:
          - Sim
        description: >-
          This API fetches the data usage details of each session made by a SIM in a particular time Interval.
           <br/><br/>```Filter Activities - By Offset and Limit (Paging)```<br/>
           Following query parameters should be supplied by client, If not provided service will return a partial response considering
           with default values of offset i.e. '0' and limit i.e. '10'. 
           <ul style='list-style-type:square'>
             <li>offset</li>
             <li>limit</li>         
           </ul>
        summary: To fetch the details of data usage sessions.
        operationId: ''
        security:
          - OAuth2ClientCredentials:
              - 'https://api.stc.com.sa/scope/appAuth/gctPlatformMgmt/sims/sessionWiseDataUsage.read'